### ISSUE TITLE
Destroyed objects are only removed locally using remove.sqf

### ISSUE THREAD

**Issue by nigeyuk** [EpochModTeam/DayZ-Epoch#1730] opened 2016-08-12 14:26 UTC
When a player has removed ore from a vein and collected it from the ground, another player can still see the rubble on his screen and also collect the ore, this has been the case several times today in testing, on both chernarus and panthera.

**Comment by vbawol** [comment] 2016-08-12 16:23
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/actions/remove.sqf#L208-L221

One simple fix maybe to just delete the destroyed vein: 
https://github.com/EpochModTeam/DayZ-Epoch/pull/1731

**Comment by ebaydayz** [comment] 2016-08-12 23:49
The rubble is already getting deleted correctly on the client that destroyed it here:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/actions/remove.sqf#L183

So attempting to delete it again on the same client won't do anything. 

The problem may be that simulation is disabled on those when they are spawned. So the destruction is not being synchronized. Although it should only be disabled on the server machine, so it is weird that is happening. 

@nigeyuk try with this line commented out and see if it still happens:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_server/compile/spawn_mineveins.sqf#L14

**Comment by oiad** [comment] 2016-08-13 00:08
This is the same with supply crates FYI

**Comment by vbawol** [comment] 2016-08-13 00:48
Oh ya thats right, The way Arma works is that these wreck models are actually spawned locally per player.

This explains two things:
1. If you delete the object its only deleted locally.
2. if you can set a variable then its only set on the local 'ruin' object.

This was never seen as a major issue and is most likely the reason for the added RNG logic to reduce chances of getting a payout.

**Comment by oiad** [comment] 2016-08-13 00:51
@ebaydayz i have a script I wrote to do something similar with lootboxes, You can still dupe but you need to be super quick/synchronized with the other player. This helps tremendously

**Comment by icomrade** [comment] 2016-08-13 02:16
Just make the wreck class a weaponholder and add a couple magazine slots?

**Comment by icomrade** [comment] 2016-08-13 17:06
Currently working on this, I'm trying to accomplish this by adding an event handler that adds the ore and gems when the vein wreck class is spawed, I also added 10 magazine classes to the wrecked vein. The location to access the gear is a little small, but it should be okay. The wreck classes will also have to be added to the server cleanup if they aren't already

**Comment by ebaydayz** [comment] 2016-08-13 17:16
@icomrade If you want to hop on discord we can test this in multiplayer. It will be easier to see exactly what the problem is.

**Comment by icomrade** [comment] 2016-08-13 17:25
The problem is wrecks are spawned locally for each client, I believe this means delete vehicle is also going to only work on the client it's called on. This means if one player removes the vein, it will still be there for everyone but that player. Switching it to a gear container means it will be handled like any other gear container and will be synced between clients. 

I won't be able to get on discord until later.

**Comment by ebaydayz** [comment] 2016-08-13 17:42
Ok. IMO it doesn't make sense to need to destroy the crate first and then use a crowbar to get the loot. The addAction currently says "Destroy %1" when it is obviously already destroyed.

It should probably be changed so you can use a crowbar to open the crate without destroying it first too.

**Comment by icomrade** [comment] 2016-08-13 17:51
I suppose we could just change this so you dont have to destroy the vein or crate first and use fn-selfactions then delete the crate or vein in remove.sqf and spawn the output on the ground, that may make more sense. We'd also need to check for other players nearby. Especially since we have a pickaxe item now. obviously it won't be as elegant but it would probably be easier on us and make more sense than shooting an ore vein

**Comment by icomrade** [comment] 2016-08-15 16:08
This covers all objects that use remove.sqf

**Comment by ebaydayz** [comment] 2016-08-15 16:23
One solution is to add another PVEH on clients that runs a deleteVehicle for the rubble. The client who performs the initial delete will send out a publicVariable with location and classname of the rubble. The other clients do a nearestObjects search of that location and delete it.

**Comment by icomrade** [comment] 2016-08-15 16:29
Yeah that's probably the best option, I was really trying to not use a PVEH, even if we do use PVEH we'd need to ensure that any delay doesn't allow duping the object removal or simultaneous removal.

**Comment by ebaydayz** [comment] 2016-08-15 16:29
Or just add deleteVehicle _this to the object's killed EH in the configs.

**Comment by icomrade** [comment] 2016-08-15 16:46
Well that would just delete it without anyone removing it?

**Comment by ebaydayz** [comment] 2016-08-15 17:41
Nevermind I'm dumb.

[[As you suggested above]](https://github.com/EpochModTeam/DayZ-Epoch/issues/1730#issuecomment-239633151) it's probably better to forgo the destruction effects, make the mine and supply crates indestructible, and just delete the non-destroyed versions when the player clicks the action with a crowbar (supply crate) or pickaxe (mine) in their inventory.

It's not as pretty, but more performance friendly.

As for other removable objects, they shouldn't be a problem as long as they don't spawn loot. It doesn't matter if their rubble is left lying around.

**Comment by icomrade** [comment] 2016-08-21 19:48
Should be good but I will close once someone confirms this is fixed with multiple players in a server.

**Comment by ebaydayz** [comment] 2016-09-04 00:39
Tested with @oiad and confirmed fixed now.

**Closed by ebaydayz** 2016-09-04 00:39 UTC
Labels: status: awaiting feedback
