### ISSUE TITLE
zombie_agent.fsm errors spamming rpt

### ISSUE THREAD

**Issue by ndavalos** [EpochModTeam/DayZ-Epoch#1810] opened 2016-12-05 13:51 UTC
I see this on client load (starting epoch, not logged into a server)
Error in expression <dayz_clientPreload and !(isNull _agent)>
  Error position: <dayz_clientPreload and !(isNull _agent)>
  Error Undefined variable in expression: dayz_clientpreload

Then I also see this after logging in and zombies spawn:
Error in expression <dayz_clientPreload and !(isNull _agent)>
  Error position: <isNull _agent)>
  Error isnull: Type Array, expected Object,Group,Display (dialog),Control,Task,Location

**Comment by ebayShopper** [comment] 2016-12-05 15:31
`Dayz_clientpreload` is defined in variables.sqf on clients. The only place it is not defined is on the server. So this happens when trying to spawn an animal or zombie agent on the server. It generates that error because they check that variable in their FSMs which are executed from their init now. Normally animals and zombies only spawn on clients. If you want to spawn them on the server you have to define that var on the server as well.

Note infistar spawns animal agents on the server and he is already aware of this problem. It should be fixed in his next update.

**Closed by ebayShopper** 2016-12-05 15:31 UTC

**Comment by ndavalos** [comment] 2016-12-05 15:39
This is not just a problem with logging into a server. When you start Arma 2 OA with the Epoch enabled in the mods this gets spammed in the RPT
Error in expression <dayz_clientPreload and !(isNull _agent)>
Error position: <dayz_clientPreload and !(isNull _agent)>
Error Undefined variable in expression: dayz_clientpreload

This is before even getting to the Arma 2 game menu. Something is wrong here where this is not initialized properly in the official version of the mod released. This problem occurs without even being connected to a server or even attempting to connect to a server.

**Comment by ndavalos** [comment] 2016-12-05 15:45
This is also not in the server RPT, ONLY the client. I'm not trying to spawn anything server side.

**Comment by AirwavesMan** [comment] 2016-12-05 15:51
I can confirm that problem @ndavalos It is client only.

**Comment by ebayShopper** [comment] 2016-12-05 16:15
Ok, it was from the intro.sqs script spawning zombies. I always start my client with -world=empty param for faster loading, so that explains why I didn't notice it before.

Fixed with 2db6692. I don't get any errors on the main menu with intro.sqs loaded now. 

Thanks for reporting.
