### ISSUE TITLE
Database Issues

### ISSUE THREAD

**Issue by looter809** [EpochModTeam/DayZ-Epoch#1870] opened 2017-01-11 00:18 UTC
Hey guys,

I have had this problem on Survival Servers and GTX Gaming since Epoch 1.0.6 came out, basically at my 6:00am (PST) restart, players keep reporting that the whole map will not load the database until the next restart. I have not been on early enough to test this myself, but I have had 3 or 4 players tell me this between the two hosts.

I do not know if GTX Gaming and Survival Servers are up to date on the Epoch releases, but does anyone else get this problem? Did Epoch B or C server files fix this?

**Comment by skotracker** [comment] 2017-01-11 00:27
We had the same issue on Survival Server for another server.  We opened a ticket and they fixed it in less than five min.  Something about moving our data or moving our extdb2 on their end which broke the connection to the database.   Hope this fixes your issue.

**Comment by ebayShopper** [comment] 2017-01-11 00:41
Sounds like a duplicate of #1822 
Fixed with this change to server_monitor and server_functions: 7e34173

This fix was not in the Build C server files release, but it should have been. Maybe we can do another server files update @icomrade.

**Closed by ebayShopper** 2017-01-11 00:41 UTC

**Comment by oiad** [comment] 2017-01-11 00:43
Sounds like it's this issue that has been fixed: Readd hive shutdown code from 1051 https://github.com/EpochModTeam/DayZ-Epoch/commit/7e341739ee2e9226016b24d19f1a605d20445901
