### ISSUE TITLE
Zombie spawn issues

### ISSUE THREAD

**Issue by DeVloek** [EpochModTeam/DayZ-Epoch#1819] opened 2016-12-11 20:54 UTC
1. Zombies are unable to move
We have noticed on several servers (both customized and uncustomized) that zombies often are unable to move. This seems to happen more often around certain objects, such as Land_Misc_GContainer_Big or Land_Misc_Cargo1Bo. Also it seems to happen more often in close quarters, not so much in open terrain. They don't move at all, even when you shoot at them. Only when you get into melee range they insta-turn to you and attack, but they don't follow. It doesn't matter if zeds are slow or fast.

2. Zombies spawn inside objects
Same as above, but they spawn inside walls, wrecks and other objects.

3. Zombies spawn and die instantly
Often we find dead zombies, although there are no high buildings nearby where they could have jumped off. It seems they spawned and instantly died.

We suspect all these bugs are somehow connected.

Here are some example screenshots of stuck zombies, from different servers:
![zombiestuck1](https://cloud.githubusercontent.com/assets/24300064/21083091/05bc79d8-bfe9-11e6-946b-f9414137ff64.jpg)
![zombiestuck2](https://cloud.githubusercontent.com/assets/24300064/21083092/05bca8ae-bfe9-11e6-9dfa-a5ea46a0e948.jpg)
![zombiestuck3](https://cloud.githubusercontent.com/assets/24300064/21083093/05c0718c-bfe9-11e6-8877-0ab1de60f9ed.jpg)
![zombiestuck4](https://cloud.githubusercontent.com/assets/24300064/21083094/05c42f0c-bfe9-11e6-9bbc-699035f634a5.jpg)
![zombiestuck5](https://cloud.githubusercontent.com/assets/24300064/21083095/05c816c6-bfe9-11e6-9b5a-a29511c15848.jpg)
![zombiestuck6](https://cloud.githubusercontent.com/assets/24300064/21083171/fa8376aa-bfea-11e6-9358-256841b10f2f.jpg)

**Comment by oiad** [comment] 2016-12-11 21:43
Do you have walking zombies turned on?

I have not experienced this on my server with walking zombies turned on

**Comment by DeVloek** [comment] 2016-12-11 21:59
Like I said: It doesn't matter if zeds are slow or fast.

**Comment by oiad** [comment] 2016-12-11 22:08
Any other changes you have made to the server? I'm not experiencing this or have heard of it is all

**Comment by ndavalos** [comment] 2016-12-12 17:32
I've experienced it, but it's pretty rare if it happens. I think I only saw it a couple times back in September, haven't noticed it happening since then.

**Comment by icomrade** [comment] 2016-12-12 18:54
I've seen this happen as well, not sure what the issue is as I haven't really looked recently. It may be fixed in a recent update to the fsm, https://github.com/DayZMod/DayZ/commit/f47d6fe5b94b96e11c26e9bf847455e0722dfc57

**Comment by ebayShopper** [comment] 2016-12-12 20:29
I can confirm this one with the new fsm too. It may be an issue with some badly placed building zedPos. I think some were added that were not included in 1051. I'll check it out.

**Comment by DeVloek** [comment] 2016-12-12 20:45
>  It may be an issue with some badly placed building zedPos.
I thought that too, so I made new zedpos coordinates for those objects where it happens very often, eg. the blue garbarge container. I placed 4 new zedpos all around the container, up to 5m away. It didn't do anything, zombies still spawned in the middle of the container and everywhere around it, not able to move.
Also it happens near buildings that don't have any zedpos at all, making new zedpos for those didn't work either.

**Comment by ebayShopper** [comment] 2016-12-12 20:51
@DeVloek - Are you testing with the new fsm? If not please try it out and let me know if it is any better for the stuck zombie issue:
https://github.com/DayZMod/DayZ/commit/f47d6fe5b94b96e11c26e9bf847455e0722dfc57

**Comment by DeVloek** [comment] 2016-12-12 21:45
Thanks, currently testing the new .fsm

**Comment by DeVloek** [comment] 2016-12-12 22:31
Nope, unfortunately the new fsm did not fix it. 

A few more observations:
The zedpos coordinate is only used for internal zombies, turning those off completely has no effect on this bug. So we did some more tests with randomized (non-internal) zombie spawn positions, and even if zombies spawn 20m away from the building that spawns them, there's a chance that they don't move. So if it isn't the position, I guess it's something in the fsm that causes this behavior?

**Comment by DeVloek** [comment] 2016-12-29 22:15
After killing and looting hundreds of zombies, I made some observations:
1. Zombies who cannot move are always named "Viral Infected"
2. Zombies who can move are never "Viral Infected", but have their original name.

There's obviously a bug with those viral zeds, so we did some further digging and found out the following:

In ViralZeds.hpp, the class Eventhandlers doesn't work. 
In line 26 theres a call for "zombie_initialize", which doesn't even exist. 
Also, in the same class in Zeds.hpp, there are 3 additional lines
`init = "_this execFSM ""\z\AddOns\dayz_code\system\zombie_agent.fsm""";`
`HandleDamage = "_this call local_zombieDamage;";`
`Killed = "[_this,'zombieKills'] call local_eventKill;";`
which are missing in ViralZeds.hpp

On our server, we used the zombie_initialize call to make a dirty fix and add back those missing lines. Works fine, now all zombies are able to walk again :)

So I guess all you gotta do to fix this, is to put the class Eventhandlers from Zeds.hpp into ViralZeds.hpp.

**Comment by ebayShopper** [comment] 2016-12-30 02:10
Nice find @DeVloek . R4z0r forgot to update the viral zeds config when he moved the zombie event handlers:
https://github.com/DayZMod/DayZ/commit/09aa9f8879b40013e852e2c8333ab2a219cff25e

Good thing you found that or we would probably be looking in circles over a simple mistake.

Certain zombies spawning and instantly dying may be unrelated. I remember seeing it before this change. It is probably due to their ZedPos being poorly placed in certain building types. The zombies would then spawn inside walls and be instantly crushed to death. You can find these bad building types by marking `allDead` on the map without filtering out corpses with no `bodyName` [example [(just set the condition to if (true) then {)](https://github.com/ebayShopper/TestKit/blob/master/testkit/ui/tk_mark.sqf#L38-L40)]. That will mark all dead animals and zombies as well. I remember seeing some buildings in downtown Berezino that had this problem. When I teleported inside there were a pile of dead zombies in the wall. 

If you find some buildings with that problem please post another issue with their classnames or screenshots of them so we can fix their zedPos. Thanks.

**Closed by ebayShopper** 2016-12-30 02:10 UTC
