### ISSUE TITLE
Another example of duplicate ObjectUID's borking a server.

### ISSUE THREAD

**Issue by justchil** [EpochModTeam/DayZ-Epoch#1602] opened 2014-12-24 08:18 UTC
I posted about this issue once before because it caused vehicles to change classes.

I just spend several hours troubleshooting an issue that prevented my server from loading objects_data.

You will see an error like:

 0:31:23 Error in expression < _countr)];
};
_countr = _countr + 1;
} forEach _objWpnTypes;
_objWpnTypes = (_i>
 0:31:23   Error position: <forEach _objWpnTypes;
_objWpnTypes = (_i>
 0:31:23   Error foreach: Type String, expected Array
 0:31:23 File z\addons\dayz_server\system\server_monitor.sqf, line 280

Using several mods like plot for life / door management etc... It will use the inventory fields to store playername/steamid data.  If you have a door with the same ObjectUID as a metal floor the metal floor will have the same inventory data as the door.

I'm not sure why this prevents the server from starting but it's definitely the cause of the issue I just dealt with.  Set the inventory of the metal floor back to [] and the server pulled all the objects_data via hive again.  I just happened to noticed that both rows had the same ObjectUID.

So I ran the following query:

SELECT *, COUNT(*) c FROM object_data GROUP BY objectUID HAVING c > 1;

I had about 15 things per server with duplicate ID's.  I doubt this is getting fixed but maybe it will show up in a google search or something and will save someone a lot of time troubleshooting.

**Comment by RimBlock** [comment] 2015-01-03 04:40
Thread started here (http://epochmod.com/forum/index.php?/topic/30634-objectuid-calculation-and-how-to-improve-it/) to discuss for any who want to join in.

**Comment by justchil** [comment] 2015-01-05 15:12
I apologize for not following up... I just have a lot of issues right now mostly with performance and skiddies.

I found this and thought it was interesting and possibly related.  I have only trace logged a few restarts mostly trying to figure out why some queries take 2-3seconds to run.

2015-01-04 00:27:21 HiveExt: [Debug] Original params: |CHILD:388:30552983570249:|
2015-01-04 00:27:21 HiveExt: [Information] Method: 388 Params: 30552983570249:
2015-01-04 00:27:21 Database: [Trace] Query [0 ms] SQL: 'SELECT `ObjectID` FROM `Object_DATA` WHERE `Instance` = 11 AND `ObjectUID` = 30552983570249'
2015-01-04 00:27:21 HiveExt: [Information] Result: ["ERROR"]

It will run this around 200x times in that one second.   If you look around the objectUID you'll notice it's missing a ' in front of the value.

I see in each server_publishVehicle:

		// GET DB ID
		_key = format["CHILD:388:%1:",_uid];

I can't figure out where it's missing the quote causing the error just yet... I'm assuming the hivedll?

**Comment by justchil** [comment] 2015-01-05 15:18
ok nevermind it seems to pass on other queries without proper syntax.  I'm guessing that just didnt return a result.

2015-01-03 21:08:58 Database: [Trace] Query [0 ms] SQL: 'SELECT `ObjectID` FROM `Object_DATA` WHERE `Instance` = 11 AND `ObjectUID` = 10131854014058'
2015-01-03 21:08:58 HiveExt: [Information] Result: ["PASS","52744"]

**Comment by RimBlock** [comment] 2015-01-06 08:17
Cool, so there is a call to return the objectID from the DB.  I do notice it is only used by the publish vehicle scripts and there is a 10 second retry timeout before it bombs out if the objectID is not received from the DB.

I may try adding it to my Take Ownership (publishFullObject) function and see how it handles a number of calls and what the turnaround is like with highish volumes.

**Comment by ebaydayz** [comment] 2016-02-23 19:26
That RPT error happens anytime server_monitor encounters an object inventory field that does not consist of either:
1. A nested array (normal for cars, safes, lockboxes, etc.)
**OR**
2. An empty array (normal for walls, plotpoles, doors, etc.)

This will never happen with a stock server.

However, several mods write non-nested arrays of strings (like UIDs) to the inventory of objects which normally have an empty inventory field (like plot poles and doors). I described it in more detail [here](http://epochmod.com/forum/index.php?/topic/16807-release-30-door-management-no-more-codes/&page=14#comment-216924).

Now if something caused the object class to swap from one which is expected to have a special inventory field (in your case the door) to one that is not expected to have a special inventory (in your case the metal floor) it would cause this error to occur. It is a major problem because it completely stops the server from loading until the object_data entry is corrected.

The root problem is the duplicate ObjectUID bug #1504 causing the class to change. However, it may also be a bug in the custom mod causing the class to change, as was the case with door management in my above post. However, if this happens on a stock server it will not error out and fail to start. The inventory will simply be wrong on the object that swapped class.

The root cause is a duplicate of #1504, so I'm going to close this and redirect discussion there.

**Closed by ebaydayz** 2016-02-23 19:26 UTC
