### ISSUE TITLE
Logging After Death

### ISSUE THREAD

**Issue by looter809** [EpochModTeam/DayZ-Epoch#1825] opened 2016-12-18 22:01 UTC
Hello, I have noticed that if you log right after dying, your body will sink into the ground and the player who killed you will not be able to loot your body. Is there any fix for this / could we see the fix in 1.0.6.1?

**Comment by ndavalos** [comment] 2016-12-18 23:13
Yeah I've been getting a lot of complaints about bodies disappearing too quickly. Way under the 40 minutes on the normal corpse cleanup.

**Comment by looter809** [comment] 2016-12-19 04:17
That too yeah. I wish the body delete scheduler could do the cleanup based on when the player died instead of every 30 minutes or whatever it is deleting all bodies on map. (Am I wrong about how the body cleanup works?)
But that isn't my problem I am having ndavalos. A couple players are glitching the system by logging out as they die to make their bodies just sink into the ground. When I have seen this glitch in person (back in 1.0.5.1) the player could then log back in and all their gear was still on their body, but I'm not sure if that is still the case.

**Comment by icomrade** [comment] 2016-12-20 00:03
The body disappearing issue that results from the player logging out has been around forever, it's part of the reason that players get kicked to the MP setup screen after a short delay (which seemed to help the issue). There's nothing we can really do about it, it's probably just the real virtuality engine cleanup kicking in.

**Comment by icomrade** [comment] 2016-12-20 00:15
I witnessed it fairly frequently in all previous builds.

**Comment by ndavalos** [comment] 2016-12-21 15:48
It appears that if you have ghosting enabled you guys are deleting the body outright without checking if it's alive or not. I put in checks for if the player object being deleted is alive and the problem went away.

**Comment by LunaCB** [comment] 2016-12-23 13:40
would you mind sharing / pulling this solution @ndavalos ?

**Comment by Clanwarfare** [comment] 2016-12-24 15:49
lol ^^^

**Comment by icomrade** [comment] 2017-01-13 13:49
Anyone re-test this after the commit above?

**Comment by ebayShopper** [comment] 2017-01-24 21:54
@ndavalos - onPlayerDisconnect does not delete any corpses regardless of whether `dayz_enableGhosting` is true or not. It uses playableUnits which does not return dead units or units awaiting respawn:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_server/compile/server_onPlayerDisconnect.sqf#L16-L20

Corpses were occasionally being deleted right away because of the issue I mentioned in d509c15, but that should be fixed with those changes to sched_corpses now.

The issue described in the OP is unrelated. It was present in 1051 and has been an issue in DayZ mod for a long time. I can reproduce it easily by letting myself die to zombies and force killing my game immediately as I die. When I log back in my body is gone. Any player in-game observing this will see the body sink into the ground as @looter809 described. If deleteVehicle were used the body would disappear instantly instead.

The issue is that DayZ mod uses [disabledAI=1](https://community.bistudio.com/wiki/Description.ext#disabledAI). So when living players disconnect Arma automatically removes their unit rather than having an AI take control of it. We've always used `respawnDelay=5;` which means there is a five second window after death when the player is considered "awaiting respawn". If they force disconnect during this window their unit will be removed by Arma the same as if they were alive.

I've changed this to `respawnDelay=0;` in 6c62b3f and after testing a dozen times I can not reproduce it anymore. I've adjusted player_death and onPlayerDisconnect, so this shouldn't cause any problems. It will still need multiplayer testing on a stressed server to be sure.

There are just a couple more things to resolve and then we should put up a 1.0.6.1 test build.

**Closed by ebayShopper** 2017-01-24 21:54 UTC
