### ISSUE TITLE
Lag when purchasing vehicles starts one hour after server restart

### ISSUE THREAD

**Issue by hnroc** [EpochModTeam/DayZ-Epoch#1604] opened 2014-12-27 02:49 UTC
when my server(epoch1.0.5.1) restart,player buy a vehicle,the vehicle Will come out soon.
but when my server run time more than 1 hour,if player bought vehicle,it come out after 5 Minutes.
why?
how to Solve?
thank you.

**Comment by Windmolders** [comment] 2015-07-03 15:33
This is server lag. Optimisation is needed.

**Comment by icomrade** [comment] 2016-07-19 02:50
I think the sleep (now uiSleep in 1.0.6) in server_publishVehicle# in combination to extremely low server fps caused the most significant portion of the delay. In combination to changing the sleep to uiSleep moving it to the bottom of the while loop should speed things up by at least 1 second 92cbd8a7a9517c2c2e5234818c81a960dacefe31

Another portion of the delay is probably the dual hive calls, which can be reduced by changing Hive calls 308 and 388. Not sure if the delay caused by having 2 calls is really worth the trouble of modifying the calls in the HiveEXT.

Anyway, I'm going to mark this as awaiting feedback, If anyone still experiences this issue with the new HiveDLL and the changes outlined above please leave a comment. Otherwise, I feel this is probably more or less fixed in most cases (aside from instances where createVehicle itself is laggy, in which case you need to configure/optimize your server properly or restart it more frequently).

**Comment by oiad** [comment] 2016-07-19 04:42
I think this seems definitely server dependant, the only lag I get regarding purchasing vehicles is sometimes they can spawn in then disappear especially if players are on the spawn point. I've never seen purchase lag at reproducible times.

I would be checking your server fps to see what's going on and how low that is, also if you are running many so missions at once this could be part of it.

On 19 July 2016 2:50:08 PM NZST, icomrade <notifications@github.com> wrote:
>I think the sleep (now uiSleep in 1.0.6) in server_publishVehicle# in
>combination to extremely low server fps caused the most significant
>portion of the delay. In combination to changing the sleep to uiSleep
>moving it to the bottom of the while loop should speed things up by at
>least 1 second 92cbd8a7a9517c2c2e5234818c81a960dacefe31
>
>Another portion of the delay is probably the dual hive calls, which can
>be reduced by changing Hive calls 308 and 388. Not sure if the delay
>caused by having 2 calls is really worth the trouble of modifying the
>calls in the HiveEXT.
>
>Anyway, I'm going to mark this as awaiting feedback, If anyone still
>experiences this issue with the new HiveDLL and the changes outlined
>above please leave a comment. Otherwise, I feel this is probably more
>or less fixed in most cases (aside from instances where createVehicle
>itself is laggy, in which case you need to configure/optimize your
>server properly or restart it more frequently).
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/EpochModTeam/DayZ-Epoch/issues/1604#issuecomment-233516452

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Closed** 2016-08-21 22:16 UTC
Labels: prio:medium, status: awaiting feedback, status:need-test, type:bug
