### ISSUE TITLE
Chainsaw Damage

### ISSUE THREAD

**Issue by Markokil321** [EpochModTeam/DayZ-Epoch#1533] opened 2014-08-16 14:36 UTC
The chainsaws are currently gamebreakingly overpowered in their current state when it comes to base raiding. They are no longer being used for faster wood harvesting, but as mass weapons of destruction. It only takes a matter of minutes to chainsaw through locked cinder bases and destroy everything inside  with one. when you have 1 or 2 players going around with farmed oil (or duped?) they can destroy or at-least breach the majority of bases on the map very quickly, this is not realistic and is causing alot of QQ.

I strongly recommend adding some sort of chance for chainsaws to break when used on cinder/metal - and then require repairs to fix or just become useless. OR reduce the damage they can do to walls/floors/doors in general? This has already been mentioned in issues before i believe, but nothing has been done about it yet.  I would do something myself but lack the knowledge ^

thanks

EDIT: just found the other issue mentioning this: #1265

**Comment by ebaydayz** [comment] 2016-02-23 16:17
Duplicate of #1265

**Closed by ebaydayz** 2016-02-23 16:17 UTC
Labels: type:enhancement
