### ISSUE TITLE
Safe contents deleting after restart.

### ISSUE THREAD

**Issue by LunchboxCharlie** [EpochModTeam/DayZ-Epoch#1422] opened 2014-07-14 14:03 UTC
I need to post a new one, because the other ones are getting closed and saying it's not "a mod issue" when it is. On vanilla epoch, safe and lock box contents are occasionally deleting after restarts. Not all the time but just some of the time. 1-2 instances every single day, 10+ people on the server.  No RPT errors at all, relating with this issue.

**Comment by ebaydayz** [comment] 2016-02-21 19:45
With https://github.com/EpochModTeam/DayZ-Epoch/commit/726e4e0c223b7bf10d27b95a8113987cedde3d39 and https://github.com/EpochModTeam/DayZ-Epoch/pull/1467 this should be fixed now.

Also duplicate of #1503

**Closed by ebaydayz** 2016-02-21 19:45 UTC
Labels: prio:high, type:bug
