### ISSUE TITLE
Vehicles Changing

### ISSUE THREAD

**Issue by Markokil321** [EpochModTeam/DayZ-Epoch#1214] opened 2014-04-28 17:23 UTC
Hello,

Not sure whether this is an Epoch issue, or a general server bug but i have noticed player vehicles will sometimes change class during a restart. - and i mean morph, not stolen, moved or swapped by a player.

For example, they had a camo suv before the restart, and after the restart their vehicle has become a land rover. (new vehicle is on the exact same location as the old one). The key to the old vehicle will then ofc also no longer be usable.

Anyone experience this problem on their server(s)?
Thanks

**Comment by ebaydayz** [comment] 2016-02-23 17:35
Duplicate of #1504 (this case is discussed there)

**Closed by ebaydayz** 2016-02-23 17:35 UTC
Labels: prio:low, type:bug
