### ISSUE TITLE
Disabling logs of non error

### ISSUE THREAD

**Issue by raziel23x** [EpochModTeam/DayZ-Epoch#1423] opened 2014-07-14 19:12 UTC
Is there a way to have the RPT not report spam from startup of none errors?

**Comment by ebaydayz** [comment] 2016-02-21 06:07
You can use the -noLogs startup parameter, but it will stop all logging including errors. 

If you mean warnings about the dayz community assets, this is a duplicate of https://github.com/EpochModTeam/DayZ-Epoch/issues/1628 which should be solved in 106.

**Closed by ebaydayz** 2016-02-21 06:07 UTC
