### ISSUE TITLE
Item STR_EQUIP_XXXX_41 listed twice

### ISSUE THREAD

**Issue by raziel23x** [EpochModTeam/DayZ-Epoch#1392] opened 2014-07-04 19:08 UTC
Item STR_EQUIP_NAME_41 listed twice
Item STR_EQUIP_DESC_41 listed twice

Okay I am looking at the src code when i pulled a serch for the two strings above

WeaponHolder.hpp line 24 is

class WeaponHolder_ItemHatchet_DZE: WeaponHolderBase {
	scope = 2;
	displayName = $STR_EQUIP_NAME_41;
	model = "\dayz_equip\models\hatchet.p3d";
	class eventHandlers {
		init = "[(_this select 0),'cfgWeapons','ItemHatchet_DZE'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
	};
};

MeleeHatchet.hpp
class MeleeHatchet_DZE: MeleeWeapon
{
	scope=2;
	melee= "true";
	autoreload=1;
	magazineReloadTime=0;
	model="\dayz_weapons\models\Hatchet_weaponized";
	picture="\dayz_equip\textures\equip_hatchet_CA.paa";
	displayName=$STR_EQUIP_NAME_41;
	droppeditem= "ItemHatchet_DZE";
	magazines[]=
	{
		"Hatchet_Swing"
	};
	handAnim[]=
	{
		"OFP2_ManSkeleton",
		"\dayz_weapons\anim\melee_hatchet_holding.rtm"
	};
	class ItemActions
	{
		class Toolbelt
		{
			text=$STR_EPOCH_PLAYER_296;
			script="spawn player_addToolbelt;";
			use[]=
			{
				"MeleeHatchet_DZE"
			};
			output[]=
			{
				"ItemHatchet_DZE"
			};
		};
	};
	class Library
	{
		libTextDesc=$STR_EQUIP_DESC_41;
	};
	descriptionShort=$STR_EQUIP_DESC_41;
};

I am trying to wrap my head around why it is listed twice instead of a different method

**Comment by ebaydayz** [comment] 2016-02-24 18:48
The problem is STR_EQUIP_NAME_41 and STR_EQUIP_DESC_41 are listed in both the dayz_weapons and dayz_equip stringtable.xml files. It is already fixed in the 1.8.6.1 versions, so it will also be fixed in Epoch when we pack them into the 1.0.6 release.

**Closed by ebaydayz** 2016-02-24 18:48 UTC
Labels: prio:low, type:bug
